name: Travis Barrett Photography
favicon: null
layout_spectrum: 0.1619510017335415
typography_spectrum: 0.4054361148737371
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.39491506619378924
  lightness: 0.3531706954818219
  saturation: 0.48818538896739483
  rhythmicContrast: 0.5099804082419723
purpose: []
